### PR TITLE
HASKELL: Allow for state to be passed into dispatcher

### PR DESCRIPTION
**Pull request by Jeff-Ciesielski**
We need a way to update local state, this seems like a decent way to
go about it and mirrors our internal communications dispatch (more or less...)

@keyme/control-systems-engineers

### CODE REVIEW

**Comment by knitHacker** [comment]
I think it would be nice to have 2 versions, one that would take an MVar and one that doesn't

**Comment by Jeff-Ciesielski** [comment]
So you mean one that takes state and one that doesn't, or one that takes MVar state and one that takes arbitrary state that is never updated?

**Comment by knitHacker** [comment]
Maybe three?

**Comment by Jeff-Ciesielski** [comment]
lol, alright, so maybe

```
 addCallbackWithState :: (Dispatcher -> (IORef (Int -> a -> IO ()))) -> (Int -> a -> b -> IO (b)) -> MVar b -> Dispatcher -> IO ()
 
 addCallbackWithContext :: (Dispatcher -> (IORef (Int -> a -> IO ()))) -> (Int -> a -> b -> IO (b)) -> b -> Dispatcher -> IO ()

 addCallback :: (Dispatcher -> (IORef (Int -> a -> IO ()))) -> (Int -> a -> IO ()) -> Dispatcher -> IO ()

```
?

**Comment by knitHacker** [comment]
I think it's a good idea, I could be convinced if you think it's too much.

**Comment by Jeff-Ciesielski** [comment]
No, it's a good idea, but I think we need to go further : plain, context, state, state+context

**Comment by knitHacker** [comment]
Sounds good to me

**Comment by knitHacker** [comment]
I think similar functions would be useful in hasklib too.

**Comment by Jeff-Ciesielski** [comment]
I'll write it up after lunch :)

**Comment by Jeff-Ciesielski** [comment]
Updated

**Comment by knitHacker** [comment]
lgtm

**Pull request merged**
